name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v.*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Skopeo
        run: sudo apt-get -y update && sudo apt-get -y install skopeo

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ${{ github.repository }}
          cacheFrom: ${{ github.repository }}
          platform: linux/arm64
          push: always
